version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "21080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fpm

  fpm:
  image: php:fpm
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
